### ISSUE TITLE
go tool link: fork/exec /usr/local/go/pkg/tool/darwin_amd64/link: no such file or directory

### ISSUE THREAD

**Issue by haizhohuang** [eisenxp/macos-golink-wrapper#4]
when i exchange the link and original_link，
go tool link tells me  no such file or directory.

Apple M1 Pro
macOS 12.3 (21E230)
Darwin 21.4.0

what can i do

**Comment by haizhohuang** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/62498056/159393327-21333dce-35a5-4f3f-a1cd-36bedd952f08.png">

**Comment by howieyuen** [comment]
work perfectly in `go version go1.16.3 darwin/amd64`,
but in `go version go1.17.8 darwin/amd64`,
`go test` can work, `go build` failed, return as follow:
```
go tool link: fork/exec /usr/local/Cellar/go/1.17.8/libexec/pkg/tool/darwin_amd64/link: no such file or directory
```

MBP Intel
macOS 12.3 (21E230)
Darwin 21.4.0

**Comment by zhijian-pro** [comment]
> work perfectly in `go version go1.16.3 darwin/amd64`, but in `go version go1.17.8 darwin/amd64`, `go test` can work, `go build` failed, return as follow:
> 
> ```
> go tool link: fork/exec /usr/local/Cellar/go/1.17.8/libexec/pkg/tool/darwin_amd64/link: no such file or directory
> ```
> 
> MBP Intel macOS 12.3 (21E230) Darwin 21.4.0

go 1.17.8  
map intel macos 12.2.1 (21D62)
can not work

**Comment by howieyuen** [comment]
> work perfectly in `go version go1.16.3 darwin/amd64`, but in `go version go1.17.8 darwin/amd64`, `go test` can work, `go build` failed, return as follow:
> 
> ```
> go tool link: fork/exec /usr/local/Cellar/go/1.17.8/libexec/pkg/tool/darwin_amd64/link: no such file or directory
> ```
> 
> MBP Intel macOS 12.3 (21E230) Darwin 21.4.0

Mac 12.3 has removed preinstalled python2, so I change to python3, it worked~
Thanks to @eisenxp

**Comment by haizhohuang** [comment]
> > work perfectly in `go version go1.16.3 darwin/amd64`, but in `go version go1.17.8 darwin/amd64`, `go test` can work, `go build` failed, return as follow:
> > ```
> > go tool link: fork/exec /usr/local/Cellar/go/1.17.8/libexec/pkg/tool/darwin_amd64/link: no such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > MBP Intel macOS 12.3 (21E230) Darwin 21.4.0
> 
> Mac 12.3 has removed preinstalled python2, so I change to python3, it worked~ Thanks to @eisenxp

it's worked! thx
